config/routes.rb
Rails.application.routes.draw do
  resources :mangas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :manga
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :manga
end

app/models/concerns/manga_searchable.rb
module MangaSearchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model

    index_name "es_manga_#{Rails.env}"

    settings analysis: self.analyzer_settings do
      mappings dynamic: 'false' do
        indexes :id,                   type: 'integer'
        indexes :publisher,            type: 'keyword'
        indexes :author,               type: 'keyword'
        indexes :category,             type: 'text', analyzer: 'kuromoji'
        indexes :title,                type: 'text', analyzer: 'katakana_analyzer'
        indexes :description,          type: 'text', analyzer: 'kuromoji'
      end
    end

    def as_indexed_json(*)
      attributes
        .symbolize_keys
        .slice(:id, :title, :description)
        .merge(publisher: publisher_name, author: author_name, category: category_name)
    end
  end

  def publisher_name
    publisher.name
  end

  def author_name
    author.name
  end

  def category_name
    category.name
  end

  class_methods do
    def create_index!
      client = __elasticsearch__.client
      client.indices.delete index: self.index_name rescue nil
      client.indices.create(index: self.index_name,
                            body: {
                                settings: self.settings.to_hash,
                                mappings: self.mappings.to_hash
                            })
    end

    # multi_matchで一つのカラムにまとめて検索した場合の挙動の確認
    def es_search(query)
      __elasticsearch__.search({
        query: {
          multi_match: {
            fields: %w(id publisher author category title),
            type: 'cross_fields',
            analyzer: 'katakana_analyzer',
            query: query,
            operator: "and"
          }
        }
      })
    end

    # TODO それぞれのフィールドに対して検索を行う。重みづけが可能か調査。    
    def manga_search_each_field
    end

    def analyzer_settings
      {
        analyzer: {
          katakana_analyzer: {
            tokenizer: 'kuromoji_tokenizer',
            filter: ['katakana_readingform', 'hiragana_to_katakana']
          }
        },
        filter: {
          katakana_readingform: {
            type: 'kuromoji_readingform',
            use_romaji: false
          },
          hiragana_to_katakana: {
            type: 'icu_transform',
            id: 'Hiragana-Katakana'
          }
        }
      }
    end
  end
end

app/models/manga.rb
class Manga < ApplicationRecord
  include MangaSearchable

  belongs_to :publisher
  belongs_to :category
  belongs_to :author
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :manga
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  before_action :set_manga, only: [:show, :edit, :update, :destroy]

  # GET /mangas
  # GET /mangas.json
  def index
    @mangas = if search_word.present?
                # scoreを確認用
                Manga.es_search(search_word).page(params[:page] || 1).per(5).records.each_with_hit { |record, hit| puts "* #{record.title}: #{hit._score}" }
                
                Manga.es_search(search_word).page(params[:page] || 1).per(5).records
              else
                Manga.page(params[:page] || 1).per(5)
              end
  end

  # GET /mangas/1
  # GET /mangas/1.json
  def show
  end

  # GET /mangas/new
  def new
    @manga = Manga.new
  end

  # GET /mangas/1/edit
  def edit
  end

  # POST /mangas
  # POST /mangas.json
  def create
    @manga = Manga.new(manga_params)

    respond_to do |format|
      if @manga.save
        format.html { redirect_to @manga, notice: 'Manga was successfully created.' }
        format.json { render :show, status: :created, location: @manga }
      else
        format.html { render :new }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mangas/1
  # PATCH/PUT /mangas/1.json
  def update
    respond_to do |format|
      if @manga.update(manga_params)
        format.html { redirect_to @manga, notice: 'Manga was successfully updated.' }
        format.json { render :show, status: :ok, location: @manga }
      else
        format.html { render :edit }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mangas/1
  # DELETE /mangas/1.json
  def destroy
    @manga.destroy
    respond_to do |format|
      format.html { redirect_to mangas_url, notice: 'Manga was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manga
      @manga = Manga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manga_params
      params.require(:manga).permit(:publisher_id, :category_id, :author_id, :title, :description)
    end

    def search_word
      @search_word ||= params[:search_word]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsEs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mangas/_form.html.erb
<%= form_with(model: manga, local: true) do |form| %>
  <% if manga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manga.errors.count, "error") %> prohibited this manga from being saved:</h2>

      <ul>
      <% manga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :publisher_id %>
    <%= form.text_field :publisher_id %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.text_field :author_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mangas/edit.html.erb
<h1>Editing Manga</h1>

<%= render 'form', manga: @manga %>

<%= link_to 'Show', @manga %> |
<%= link_to 'Back', mangas_path %>

app/views/mangas/index.html.erb
<p id="notice"><%= notice %></p>

<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        漫画検索
      </h1>
    </div>
  </div>
</section>

<div class="container" style="margin-top: 30px">
  <%= form_tag(mangas_path, method: :get, class: "field has-addons has-addons-centered") do %>
    <div class="control">
      <%= text_field_tag :search_word, @search_word, class: "input", placeholder: "漫画を検索する" %>
    </div>
    <div class="control">
      <%= submit_tag "検索", class: "button is-info" %>
    </div>
  <% end %>
</div>

<div class="container" style="margin-top: 50px">
  <table class="table is-striped is-hoverable">
    <thead class="has-background-info">
      <tr>
        <th class="has-text-white-bis">出版社</th>
        <th class="has-text-white-bis">ジャンル</th>
        <th class="has-text-white-bis">著者</th>
        <th class="has-text-white-bis">タイトル</th>
        <th class="has-text-white-bis">説明</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @mangas.each do |manga| %>
        <tr>
          <td><%= manga.publisher.name %></td>
          <td><%= manga.category.name %></td>
          <td><%= manga.author.name %></td>
          <td><%= manga.title %></td>
          <td><%= manga.description %></td>
          <td><%= link_to 'Show', manga %></td>
          <td><%= link_to 'Edit', edit_manga_path(manga) %></td>
          <td><%= link_to 'Destroy', manga, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= paginate @mangas %>
</div>

app/views/mangas/new.html.erb
<h1>New Manga</h1>

<%= render 'form', manga: @manga %>

<%= link_to 'Back', mangas_path %>

app/views/mangas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Publisher:</strong>
  <%= @manga.publisher %>
</p>

<p>
  <strong>Category:</strong>
  <%= @manga.category %>
</p>

<p>
  <strong>Author:</strong>
  <%= @manga.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @manga.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @manga.description %>
</p>

<%= link_to 'Edit', edit_manga_path(@manga) %> |
<%= link_to 'Back', mangas_path %>